### PR TITLE
Create koo_jung.html

### PR DESCRIPTION
**Pull request by koolimy**
Jung Koo's webpage

### CODE REVIEW

**Comment by koolimy2** [comment]
I was looking at your code, and I think there can be a few changes:

1. the <a ref .......> stuff should probably be changed to just /Jung.jpg, rather than IP address/Jung.jpg. The syntax /picname.jpg works for both internal and external, whereas the IP address/picname.jpg might not work. We who are inside the home network can't connect if we use the external public IP to access, 

2. "**<br.......>**" doesn't need a "</br........>"

3. Does the <p title ...> stuff work? you can probably see if your html works on your own, by saving the txt as an .html file and opening with a web browser.

**Comment by koolimy** [comment]
Empty HTML Elements
HTML elements with no content are called empty elements.
"<br...>" is an empty element without a closing tag (the "<br...>" tag defines a line break).
Empty elements can be "closed" in the opening tag like this: "<br /....>".
HTML5 does not require empty elements to be closed. But if you want stricter validation, or if you need to make your document readable by XML parsers, you must close all HTML elements properly.

**Comment by koolimy2** [comment]
That sounds good. I guess it's probably better to then close <br .....> using </br.....>

**Comment by koolimy** [comment]
The <p title ...> stuff should work, and the format should be

"<p title="words you want to write"...>"

**Comment by koolimy** [comment]
Note, <br...> should be closed using <br/ ...>

**Comment by koolimy** [comment]
The w3schools site is really good, their editor you can 실시간 check your html code

https://www.w3schools.com/html/tryit.asp?filename=tryhtml_paragraphs2

You can edit any part of the code and run it and it will show

**Comment by koolimy2** [comment]
I think some of the good comments here should be moved to the issues tab, so they can survive a merge to the main branch.

**Comment by koolimy2** [comment]
I think your pull is good to merge 👍 🤓

**Pull request merged**
